//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "cuadrilla")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub lider_cuadrilla_id: Option<i32>,
    pub lote: String,
    pub variedad_id: Option<i32>,
    pub temporada_id: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::jornalero::Entity",
        from = "Column::LiderCuadrillaId",
        to = "super::jornalero::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    Jornalero,
    #[sea_orm(
        has_many = "super::jornalero::Entity",
        from = "Column::Id",
        to = "super::jornalero::Column::CuadrillaId"
    )]
    Jornaleros,
    #[sea_orm(has_many = "super::produccion::Entity")]
    Produccion,
    #[sea_orm(
        belongs_to = "super::temporada::Entity",
        from = "Column::TemporadaId",
        to = "super::temporada::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Temporada,
    #[sea_orm(
        belongs_to = "super::variedad::Entity",
        from = "Column::VariedadId",
        to = "super::variedad::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Variedad,
}

impl Related<super::jornalero::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Jornaleros.def()
    }
}

impl Related<super::produccion::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Produccion.def()
    }
}

impl Related<super::temporada::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Temporada.def()
    }
}

impl Related<super::variedad::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Variedad.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
