//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::cliente::Entity as Cliente;
pub use super::cuadrilla::Entity as Cuadrilla;
pub use super::jornalero::Entity as Jornalero;
pub use super::produccion::Entity as Produccion;
pub use super::temporada::Entity as Temporada;
pub use super::tipo_empaque::Entity as TipoEmpaque;
pub use super::tipo_uva::Entity as TipoUva;
pub use super::variedad::Entity as Variedad;
