//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::cuadrilla::Entity as Cuadrilla;
pub use super::jornalero::Entity as Jornalero;
pub use super::produccion::Entity as Produccion;
pub use super::temporada::Entity as Temporada;
