//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "produccion")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub fecha: Date,
    pub cuadrilla_id: i32,
    pub temporada_id: i32,
    #[sea_orm(column_type = "Decimal(Some((15, 3)))")]
    pub cantidad: Decimal,
    pub cajas_no_aceptadas: Option<i32>,
    pub created_at: Option<DateTimeUtc>,
    pub updated_at: Option<DateTimeUtc>,
    pub tipo_empaque_id: Option<i32>,
    pub tipo_uva_id: Option<i32>,
    pub cliente_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cuadrilla::Entity",
        from = "Column::CuadrillaId",
        to = "super::cuadrilla::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Cuadrilla,
    #[sea_orm(
        belongs_to = "super::temporada::Entity",
        from = "Column::TemporadaId",
        to = "super::temporada::Column::Id",
        on_update = "Cascade",
        on_delete = "Restrict"
    )]
    Temporada,
}

impl Related<super::cuadrilla::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Cuadrilla.def()
    }
}

impl Related<super::temporada::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Temporada.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
